In [14]:
import numpy as np 
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
b = np.array([[ 1, 3, 5 ] , [ 2, 4, 6 ]])
print(b)

[[1 3 5]
 [2 4 6]]


In [17]:
a.dtype

dtype('int64')

In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
a.shape

(5,)

In [ ]:
a.itemsize

8

In [15]:
b.dtype

dtype('int64')

In [13]:
a.nbytes

40

In [20]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [21]:
b[0][1]

3

In [22]:
b[1][2]

6

In [23]:
b.reshape(3, 2)

array([[1, 3],
       [5, 2],
       [4, 6]])

In [24]:
b.swapaxes(0, 1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
c = b.flatten()
c

array([1, 3, 5, 2, 4, 6])

In [27]:
np.sort(c)

array([1, 2, 3, 4, 5, 6])

In [30]:
data = np.arange(0, 1000)
print(data.dtype)

int64
